[package]
name = "rquickjs"
version = "0.0.4"
authors = ["Mees Delzenne <mees.delzenne@gmail.com>"]
edition = "2018"
license = "MIT"
readme = "README.md"
description = "High level bindings to the quickjs javascript engine"
repository = "https://github.com/DelSkayn/rquickjs.git"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rquickjs-sys = { version = "0.0.3", path = "./rquickjs-sys/" }
quick-error = "1.2.3"
libc = "0.2.67"
fxhash = "0.2.1"

[workspace]
members = [
    "./rquickjs-sys"
]

[features]
parallel = ["rquickjs-sys/parallel"]
exports = ["rquickjs-sys/exports"]

[dev-dependencies]
trybuild = "1.0.23"
