[package]
name = "rquickjs"
version = "0.0.5"
authors = ["Mees Delzenne <mees.delzenne@gmail.com>"]
edition = "2018"
license = "MIT"
readme = "README.md"
description = "High level bindings to the quickjs javascript engine"
repository = "https://github.com/DelSkayn/rquickjs.git"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quick-error = "1.2.3"
fxhash = "0.2.1"

[dependencies.rquickjs-sys]
version = "0.0.4"
path = "./rquickjs-sys"

[dependencies.tokio-rs]
package = "tokio"
version = "^0.3"
optional = true
default-features = false
features = ["rt"]

[dependencies.async-std-rs]
package = "async-std"
version = "^1.7"
optional = true
default-features = false
features = ["default", "unstable"]

[dependencies.dlopen]
version = "^0.1"
optional = true

[dependencies.relative-path]
version = "^1.3"
optional = true

[workspace]
members = [
    "./rquickjs-sys"
]

[features]
default = ["exports"]

# Use bindgen to generate bindings at compile-type
# otherwise bundled bindings will be used
bindgen = ["rquickjs-sys/bindgen"]

# Enable support of parallel execution
parallel = ["rquickjs-sys/parallel"]

# Enable support of reading module exports
exports = ["rquickjs-sys/exports"]

# Enable user-defined module loader support
loader = ["relative-path"]

# Enable native module loading support
dyn-load = ["loader", "dlopen"]

# Enable user-defined allocator support
allocator = []

# Use Rust global allocator by default
# otherwise libc allocator will be used
rust-alloc = ["allocator"]

# Enable interop between Rust futures and JS Promises
futures = []

# Enable Tokio async runtime support
tokio = ["futures", "tokio-rs"]

# Enable Async-std runtime support
async-std = ["futures", "async-std-rs"]

# Enable compilation tests
compile-tests = []

[dev-dependencies]
trybuild = "1.0.23"
