[package]
name = "rquickjs"
version = "0.1.0"
authors = ["Mees Delzenne <mees.delzenne@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quickjs-sys = { path = "./quickjs-sys/" }
quick-error = "1.2.3"
libc = "0.2.67"
derivative = "1.0.3"
